services:
  java_db:
    image: gvenzl/oracle-xe:21.3.0
    container_name: java_db
    ports:
      - 1521:1521
    environment:
      ORACLE_USER: SYSTEM
      ORACLE_PASSWORD: 59842*
      ORACLE_DATABASE: CRUDLIBROS
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'exit' | sqlplus -S SYSTEM/59842*@localhost:1521/CRUDLIBROS"]
      interval: 15s
      timeout: 10s
      retries: 10

  java_app:
    container_name: java_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:oracle:thin:@//java_db:1521/CRUDLIBROS
      - DATABASE_USERNAME=SYSTEM
      - DATABASE_PASSWORD=59842*
    depends_on:
      java_db:
        condition: service_healthy
